# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
      - master

variables:
- group: keyvault4testing
- group: ossrh

steps:
- task: DownloadSecureFile@1
  name: signingPrivatekey
  inputs:
    secureFile: 'signing-privatekey.asc'

- task: CmdLine@2
  inputs:
    script: 'gpg --import $(signingPrivatekey.secureFilePath)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud srempfer-github'
    organization: 'srempfer'
    scannerMode: 'Other'

- task: Maven@3
  env:
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_URI: $(keyvault-uri)
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_CLIENT_ID: $(keyvault-client-id)
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_CLIENT_KEY: $(keyvault-client-key)
    GPG_PASSPHRASE: $(gpg-passphrase)
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-s settings-ci.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: |
      **/surefire-reports/TEST-*.xml
      **/failsafe-reports/TEST-*.xml
    sonarQubeRunAnalysis: true
    goals: 'clean package'

# https://github.com/MicrosoftDocs/vsts-docs/issues/2914#issuecomment-560448579
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: |
      **/surefire-reports/TEST-*.xml
      **/failsafe-reports/TEST-*.xml
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true
