# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
      - master

strategy:
  matrix:
    jdk8:
      jdk_version: "1.8"
    jdk11:
      jdk_version: "1.11"
    jdk16:
      jdk_version: "1.16"
  maxParallel: 2

variables:
- group: keyvault4testing
- group: another-keyvault4testing
- group: ossrh

steps:
- task: DownloadSecureFile@1
  name: signingPrivatekey
  inputs:
    secureFile: 'signing-privatekey.asc'

- task: CmdLine@2
  inputs:
    script: 'gpg --import $(signingPrivatekey.secureFilePath)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud srempfer-github'
    organization: 'srempfer'
    scannerMode: 'Other'

- task: Maven@3
  env:
    # used for keyvault profile
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_URI: $(keyvault-uri)
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_CLIENT_ID: $(keyvault-client-id)
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_CLIENT_KEY: $(keyvault-client-key)
    SPRING_CLOUD_CONFIG_SERVER_AZURE_KEYVAULT_TENANT_ID: $(keyvault-tenant-id)

    # used for composite profile
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE: native
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH-LOCATIONS: classpath:/config-data/,classpath:/config-data/{application}/
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_TYPE: keyvault
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_URI: $(keyvault-uri)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_CLIENT_ID: $(keyvault-client-id)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_CLIENT_KEY: $(keyvault-client-key)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_TENANT_ID: $(keyvault-tenant-id)

    # used for composite profile with multiple Key Vault backends
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_2_TYPE: keyvault
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_2_URI: $(another-keyvault-uri)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_2_CLIENT_ID: $(another-keyvault-client-id)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_2_CLIENT_KEY: $(another-keyvault-client-key)
    SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_2_TENANT_ID: $(another-keyvault-tenant-id)

    GPG_PASSPHRASE: $(gpg-passphrase)
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-s settings-ci.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdk_version)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: |
      **/surefire-reports/TEST-*.xml
      **/failsafe-reports/TEST-*.xml
    sonarQubeRunAnalysis: true
    goals: 'clean verify'

# https://github.com/MicrosoftDocs/vsts-docs/issues/2914#issuecomment-560448579
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: |
      **/surefire-reports/TEST-*.xml
      **/failsafe-reports/TEST-*.xml
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true
